// Deliberately uses bundled/default fonts so conformance is independent of the
// runner's system font inventory. The multilingual extraction fixture is
// compiled separately by the release workflow.
#set document(
  title: "Typsastra Enhanced Unicode Engine PDF standards validation",
  author: "Typsastra contributors",
)
#set text(lang: "en")
#set page(paper: "a4", margin: 24mm)

= Enhanced Unicode Engine PDF standards validation

This directly authored document verifies that every PDF mode exposed by the
enhanced Typst CLI can be generated by every supported release binary.

== Accessible structure

The document has a language, title, author, ordered heading hierarchy, and
ordinary readable text so PDF/UA and archival profiles are tested without
depending on optional system fonts or external assets.

- Logical text remains searchable.
- Tagged structure remains available to assistive technology.
- Embedded fonts keep the document portable.

